### ISSUE TITLE
Still hitting "jmGLobalProperties" case issue...

### ISSUE THREAD

**Issue by jjou1** [jmeter-gradle-plugin/jmeter-gradle-plugin#107]
Issue:  
           //jmGlobalProperties
            if (project.jmeter.jmG**L**obalProperties != null) {
                project.jmeter.jmG**l**obalProperties.each { property -> args.add("-G" + property) }
            }

The letter should lower case "l" not upper case "L". This property code is broken and needs to be fixed asap...

Hi there, I see the fixes merged to master branch. But I am still hitting the same issues while running tests...:
09:53:32.901 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':jmRun'.
09:53:32.901 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not get unknown property '**jmGLobalProperties**' for object of type net.foragerr.jmeter.gradle.plugins.JMPluginExtension.

I have tried to clean up the existing binaries:

1.  rm -rf $HOME/.gradle/caches/ and gradle build --refresh-dependencies
2. gradle clean build --refresh-dependencies

Have the fixed being built into the gradle package to be downloaded yet?

**Comment by xfabre** [comment]
With 
```
plugins {
    id "net.foragerr.jmeter" version "1.0.9-3.3"
}
```

hitting

```
./gradlew jmRun --stacktrace
...
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'jmGLobalProperties' for object of type net.foragerr.jmeter.gradle.plugins.JMPluginExtension.
        at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:88)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:62)
        at net.foragerr.jmeter.gradle.plugins.JMPluginExtension_Decorated.getProperty(Unknown Source)
        at net.foragerr.jmeter.gradle.plugins.TaskJMRun.executeJmeterTest(TaskJMRun.groovy:90)
        at net.foragerr.jmeter.gradle.plugins.TaskJMRun.jmRun(TaskJMRun.groovy:24)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
```

**Comment by ghost** [comment]
what happens if you create an empty list in the jmeter config called jmGLobalProperties?

**Comment by xfabre** [comment]
with
```
jmeter {
...
    jmGLobalProperties = []
...
}
```
I get
```
Caused by: groovy.lang.MissingPropertyException: Could not set unknown property 'jmGLobalProperties' for object of type net.foragerr.jmeter.gradle.plugins.JMPluginExtension.
        at org.gradle.internal.metaobject.AbstractDynamicObject.setMissingProperty(AbstractDynamicObject.java:120)
        at org.gradle.internal.metaobject.ConfigureDelegate.setProperty(ConfigureDelegate.java:108)
```

**Comment by ghost** [comment]
I suggest you use an earlier release. My guess is the latest binaries containing the fix are not available. 

@foragerr are the latest binaries available for download?

**Comment by xfabre** [comment]
Thanks @nvonop .
I'm waiting for the latest binaries as my jmx files written with jmeter 3.2 are not runnable with a previous version.
cheers.

**Comment by jjou1** [comment]
When would be new release available to resolve this blocking issue? Please advice!!!

**Comment by foragerr** [comment]
@nvonop @xfabre @jjou1 Please use [v1.0.10-3.3](https://plugins.gradle.org/plugin/net.foragerr.jmeter/1.0.10-3.3)

Sorry about the delay. Time has suddenly become rather scarce.
