### ISSUE TITLE
getting XmlPullParser error

### ISSUE THREAD

**Issue by birajendunetskope** [jmeter-gradle-plugin/jmeter-gradle-plugin#110]
Here is the log snippet
`2017/11/19 22:45:48 ERROR - jmeter.JMeter: Error in NonGUIDriver com.thoughtworks.xstream.io.StreamException: Cannot create XmlPullParser
	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:56)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1061)
	at org.apache.jmeter.save.SaveService.readTree(SaveService.java:559)
	at org.apache.jmeter.save.SaveService.loadTree(SaveService.java:537)
	at org.apache.jmeter.JMeter.runNonGui(JMeter.java:750)
	at org.apache.jmeter.JMeter.startNonGui(JMeter.java:737)
	at org.apache.jmeter.JMeter.start(JMeter.java:395)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.jmeter.NewDriver.main(NewDriver.java:264)
`

**Comment by birajendunetskope** [comment]
Not getting this error any more.
