### ISSUE TITLE
jmeter, gradle on jenkins running on an EC2 instance ...  Unable to get local host IP address

### ISSUE THREAD

**Issue by cmacgowan** [jmeter-gradle-plugin/jmeter-gradle-plugin#111]
Hello foragerr - 

Thanks for the jmeter-gradle-plugin! It's working very nice locally. We are having some issues running on jenkins on an AWS EC2 instance. We are seeing the following exception and we are seeing the following log from jmeter. 

Maybe a question for the jmeter folks - I'll also write to them :-) 
Thanks for your help ... 

jmeter log (partial):

```
java.net.UnknownHostException: ip-10-97-11-202: ip-10-97-11-202: No address associated with hostname
        at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
        at org.apache.jmeter.util.JMeterUtils.getLocalHostDetails(JMeterUtils.java:1071)
        at org.apache.jmeter.util.JMeterUtils.getLocalHostIP(JMeterUtils.java:1037)
```

jmeter log (partial): 

```
2017-12-12 17:43:51.190  INFO   --- [main] org.apache.jmeter.util.JMeterUtils       : Setting Locale to en_US
2017-12-12 17:43:51.207  INFO   --- [main] org.apache.jmeter.JMeter                 : Copyright (c) 1998-2017 The Apache Software Foundation
2017-12-12 17:43:51.208  INFO   --- [main] org.apache.jmeter.JMeter                 : Version 3.3 r1808647
2017-12-12 17:43:51.209  INFO   --- [main] org.apache.jmeter.JMeter                 : java.version=1.8.0_144
2017-12-12 17:43:51.209  INFO   --- [main] org.apache.jmeter.JMeter                 : java.vm.name=Java HotSpot(TM) 64-Bit Server VM
2017-12-12 17:43:51.209  INFO   --- [main] org.apache.jmeter.JMeter                 : os.name=Linux
2017-12-12 17:43:51.209  INFO   --- [main] org.apache.jmeter.JMeter                 : os.arch=amd64
2017-12-12 17:43:51.209  INFO   --- [main] org.apache.jmeter.JMeter                 : os.version=4.9.27-14.33.amzn1.x86_64
2017-12-12 17:43:51.210  INFO   --- [main] org.apache.jmeter.JMeter                 : file.encoding=UTF-8
2017-12-12 17:43:51.210  INFO   --- [main] org.apache.jmeter.JMeter                 : Max memory     =514850816
2017-12-12 17:43:51.210  INFO   --- [main] org.apache.jmeter.JMeter                 : Available Processors =8
2017-12-12 17:43:51.214  INFO   --- [main] org.apache.jmeter.JMeter                 : Default Locale=English (United States)
2017-12-12 17:43:51.214  INFO   --- [main] org.apache.jmeter.JMeter                 : JMeter  Locale=English (United States)
2017-12-12 17:43:51.214  INFO   --- [main] org.apache.jmeter.JMeter                 : JMeterHome=/var/lib/jenkins/jobs/scale perf test regression/workspace/build/jmeter
2017-12-12 17:43:51.215  INFO   --- [main] org.apache.jmeter.JMeter                 : user.dir  =/var/lib/jenkins/jobs/scale perf test regression/workspace/build/jmeter
2017-12-12 17:43:51.215  INFO   --- [main] org.apache.jmeter.JMeter                 : PWD       =/var/lib/jenkins/jobs/scale perf test regression/workspace/build/jmeter
2017-12-12 17:43:51.233 ERROR   --- [main] org.apache.jmeter.util.JMeterUtils       : Unable to get local host IP address.
```

Gradle configuration (partial): 

```
apply plugin: "net.foragerr.jmeter"

group = 'central-tech-platform'
archivesBaseName = rootProject.name
version = System.getenv("APPLICATION_VERSION") ?: "1.0-SNAPSHOT"

buildscript {
  repositories {
   jcenter()
   maven { url 'https://plugins.gradle.org/m2/' }
  }
  dependencies {
    classpath "io.spring.gradle:dependency-management-plugin:1.0.2.RELEASE"
    classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.4.0"
    classpath "org.springframework.boot:spring-boot-gradle-plugin:1.5.4.RELEASE"
    classpath "com.netflix.nebula:gradle-ospackage-plugin:2.2.6" 
    classpath "gradle.plugin.net.foragerr.jmeter:jmeter-gradle-plugin:1.0.10-3.3"
  }
}

jmeter {
      testFileDir = file("resources/scale-test")
      jmPropertyFile = file("resources/scale-test/user.properties")
      // jmSystemPropertiesFiles= [file("/reactor-test/resources/scale-test/jmetertest.properties")] //to add additional system properties
      //enableExtendedReports = true //produce Graphical and CSV reports
  }

```

We are attempting to override the httpclient.localaddress located in the jmeter.properties by using the user.properties.

```
# Define the local host address to be used for multi-homed hosts
# We are attempting to override this from jmeter.properties
httpclient.localaddress=localhost
```

That's it :-) 
Any help is appreciated. 
Thanks
Chris

**Comment by foragerr** [comment]
Hmm that's strange, I haven't had any issues running bare jmeter 3.3 on ec2's which makes me wonder if this is something with the plugin. Will attempt to reproduce. You're not seeing this issue with local runs?

What AMI are you using?

**Comment by cmacgowan** [comment]
Hi - 

Thanks for looking ... 
Jmeter running on  t2.2xlarge instance

Here is the partial local log ... to prove it's working locally :-) 
I can also send more log details from AWS if you like. 
Getting more help from AWS / network folks here. 
I'll keep you posted. 
Thanks, 
Chris

```
2017-12-14 11:09:54.283  INFO   --- [           main] org.apache.jmeter.util.JMeterUtils       : Setting Locale to en_US
2017-12-14 11:09:54.304  INFO   --- [           main] org.apache.jmeter.JMeter                 : Copyright (c) 1998-2017 The Apache Software Foundation
2017-12-14 11:09:54.304  INFO   --- [           main] org.apache.jmeter.JMeter                 : Version 3.3 r1808647
2017-12-14 11:09:54.306  INFO   --- [           main] org.apache.jmeter.JMeter                 : java.version=1.8.0_144
2017-12-14 11:09:54.306  INFO   --- [           main] org.apache.jmeter.JMeter                 : java.vm.name=Java HotSpot(TM) 64-Bit Server VM
2017-12-14 11:09:54.306  INFO   --- [           main] org.apache.jmeter.JMeter                 : os.name=Windows 7
2017-12-14 11:09:54.306  INFO   --- [           main] org.apache.jmeter.JMeter                 : os.arch=amd64
2017-12-14 11:09:54.306  INFO   --- [           main] org.apache.jmeter.JMeter                 : os.version=6.1
2017-12-14 11:09:54.306  INFO   --- [           main] org.apache.jmeter.JMeter                 : file.encoding=Cp1252
2017-12-14 11:09:54.306  INFO   --- [           main] org.apache.jmeter.JMeter                 : Max memory     =514850816
2017-12-14 11:09:54.307  INFO   --- [           main] org.apache.jmeter.JMeter                 : Available Processors =4
2017-12-14 11:09:54.313  INFO   --- [           main] org.apache.jmeter.JMeter                 : Default Locale=English (United States)
2017-12-14 11:09:54.314  INFO   --- [           main] org.apache.jmeter.JMeter                 : JMeter  Locale=English (United States)
2017-12-14 11:09:54.314  INFO   --- [           main] org.apache.jmeter.JMeter                 : JMeterHome=C:\workspace\akkadia\reactor-test\build\jmeter
2017-12-14 11:09:54.314  INFO   --- [           main] org.apache.jmeter.JMeter                 : user.dir  =C:\workspace\akkadia\reactor-test\build\jmeter
2017-12-14 11:09:54.315  INFO   --- [           main] org.apache.jmeter.JMeter                 : PWD       =C:\workspace\akkadia\reactor-test\build\jmeter
2017-12-14 11:09:54.325  INFO   --- [           main] org.apache.jmeter.JMeter                 : IP: 10.208.120.111 Name: UC196737-TPL-A FullName: UC196737-TPL-A.ten.thomsonreuters.com

2017-12-14 11:09:54.328  INFO   --- [           main] org.apache.jmeter.JMeter                 : Adding to classpath and loader: /C:/Users/uc196737/.gradle/caches/modules-2/files-2.1/kg.apc/jmeter-plugins-standard/1.4.0/c75eb033bc7619085aab89c57f6f4bcdc37b095e/jmeter-plugins-standard-1.4.0.jar
2017-12-14 11:09:54.328  INFO   --- [           main] org.apache.jmeter.JMeter                 : Adding to classpath and loader: /C:/Users/uc196737/.gradle/caches/modules-2/files-2.1/kg.apc/jmeter-plugins-extras/1.4.0/b29fe2225586e53d98e5f3cdf0e0fe1fe689e9b0/jmeter-plugins-extras-1.4.0.jar
2017-12-14 11:09:54.329  INFO   --- [           main] org.apache.jmeter.JMeter                 : Adding to classpath and loader: /C:/Users/uc196737/.gradle/caches/modules-2/files-2.1/kg.apc/jmeter-plugins-common/1.4.0/1fd66fb629305335ae8f3e71c36c06790875bddf/jmeter-plugins-common-1.4.0.jar
2017-12-14 11:09:54.330  INFO   --- [           main] org.apache.jmeter.JMeter                 : Adding to classpath and loader: /C:/Users/uc196737/.gradle/caches/modules-2/files-2.1/kg.apc/jmeter-plugins-extras-libs/1.4.0/ff8855e5ac9261d94e73fea1110e672d30a55c57/jmeter-plugins-extras-libs-1.4.0.jar
2017-12-14 11:09:54.331  INFO   --- [           main] org.apache.jmeter.JMeter                 : Adding to classpath and loader: /C:/Users/uc196737/.gradle/caches/modules-2/files-2.1/kg.apc/jmeter-plugins-webdriver/1.4.0/3c1ac0985f455d0be1e4fb4c7de8ab5564b244e6/jmeter-plugins-webdriver-1.4.0.jar
2017-12-14 11:09:54.332  INFO   --- [           main] org.apache.jmeter.JMeter                 : Adding to classpath and loader: /C:/Users/uc196737/.gradle/caches/modules-2/files-2.1/org.apache.jmeter/ApacheJMeter_components/3.3/a6802a7c2e45cde6e2d28aeb80112673d7c3905e/ApacheJMeter_components-3.3.jar
2017-12-14 11:09:54.333  INFO   --- [           main] org.apache.jmeter.JMeter                 : Adding to classpath and loader: /C:/Users/uc196737/.gradle/caches/modules-2/files-2.1/org.apache.jmeter/ApacheJMeter_http/3.3/cf71419ae5d286a216072665ec77068821ecbc20/ApacheJMeter_http-3.3.jar
2017-12-14 11:09:54.333  INFO   --- [           main] org.apache.jmeter.JMeter                 : Adding to classpath and loader: /C:/Users/uc196737/.gradle/caches/modules-2/files-2.1/org.apache.jmeter/ApacheJMeter_jdbc/3.3/69eecdfb49f2e62524e4a1c00d46610e9065c2e2/ApacheJMeter_jdbc-3.3.jar
2017-12-14 11:09:54.334  INFO   --- [           main] org.apache.jmeter.JMeter                 : Adding to classpath and loader: /C:/Users/uc196737/.gradle/caches/modules-2/files-2.1/org.apache.Creating summariser <summary>
Created the tree successfully using C:\workspace\akkadia\reactor-test\resources\scale-test\marduk\ListRetrieval.jmx
Starting the test @ Thu Dec 14 11:09:54 CST 2017 (1513271394939)
2017-12-14 11:09:54.941  INFO   --- [ardJMeterEngine] o.a.jmeter.engine.StandardJMeterEngine   : Running the test!
2017-12-14 11:09:54.943  INFO   --- [ardJMeterEngine] org.apache.jmeter.samplers.SampleEvent   : List of sample_variables: []
2017-12-14 11:09:54.943  INFO   --- [ardJMeterEngine] org.apache.jmeter.samplers.SampleEvent   : List of sample_variables: []
Waiting for possible Shutdown/StopTestNow/Heapdump message on port 4445
2017-12-14 11:09:56.429  INFO   --- [ardJMeterEngine] o.a.jmeter.reporters.ResultCollector     : Folder at C:\workspace\akkadia\reactor-test\build\jmeter\results was created
2017-12-14 11:09:56.443  INFO   --- [ardJMeterEngine] org.apache.jmeter.JMeter                 : Running test (1513271396443)
2017-12-14 11:09:56.548  INFO   --- [ardJMeterEngine] o.a.jmeter.engine.StandardJMeterEngine   : Starting ThreadGroup: 1 : RootRetrievalList thread group
2017-12-14 11:09:56.548  INFO   --- [ardJMeterEngine] o.a.jmeter.engine.StandardJMeterEngine   : Starting 2 threads for group RootRetrievalList thread group.
2017-12-14 11:09:56.548  INFO   --- [ardJMeterEngine] o.a.jmeter.engine.StandardJMeterEngine   : Test will stop on error
2017-12-14 11:09:56.549  INFO   --- [ardJMeterEngine] org.apache.jmeter.threads.ThreadGroup    : Starting thread group... number=1 threads=2 ramp-up=1 perThread=500.0 delayedStart=false
2017-12-14 11:09:56.554  INFO   --- [ardJMeterEngine] org.apache.jmeter.threads.ThreadGroup    : Started thread group number 1
2017-12-14 11:09:56.554  INFO   --- [ardJMeterEngine] o.a.jmeter.engine.StandardJMeterEngine   : All thread groups have been started
2017-12-14 11:09:56.557  INFO   --- [hread group 1-1] org.apache.jmeter.threads.JMeterThread   : Thread started: RootRetrievalList thread group 1-1
2017-12-14 11:09:56.561  INFO   --- [hread group 1-1] o.a.j.p.java.sampler.JUnitSampler        : Trying to find constructor with one String parameter returned error: com.trgr.quality.scale.testcases.marduk.2017-12-14 11:09:58.281  INFO   --- [hread group 1-1] c.t.q.s.t.marduk.RetrieveRootsV2         : Retrieving all root folders at page 0: Expected 100.
2017-12-14 11:09:58.315  INFO   --- [hread group 1-2] c.t.q.s.t.marduk.RetrieveRootsV2         : Retrieving all root folders at page 0: Expected 100.
2017-12-14 11:09:58.488  INFO   --- [hread group 1-1] c.t.q.s.t.marduk.RetrieveRootsV2         : Actual Retrieved Root folder size: 2
2017-12-14 11:09:58.488  INFO   --- [hread group 1-1] c.t.q.s.t.marduk.RetrieveRootsV2         : tear down
2017-12-14 11:09:58.501  INFO   --- [hread group 1-2] c.t.q.s.t.marduk.RetrieveRootsV2         : Actual Retrieved Root folder size: 2
2017-12-14 11:09:58.501  INFO   --- [hread group 1-2] c.t.q.s.t.marduk.RetrieveRootsV2         : tear down
com.trgr.quality.scale.testcases.marduk.RetrieveRootsV2: Exiting tearDown() at: Thu Dec 14 11:10:00 CST 2017
2017-12-14 11:10:00.057  INFO   --- [hread group 1-2] org.apache.jmeter.reporters.Summariser   : summary +      1 in 00:00:04 =    0.3/s Avg:   186 Min:   186 Max:   186 Err:     0 (0.00%) Active: 2 Started: 2 Finished: 0
summary +      1 in 00:00:04 =    0.3/s Avg:   186 Min:   186 Max:   186 Err:     0 (0.00%) Active: 2 Started: 2 Finished: 0
2017-12-14 11:10:00.057  INFO   --- [hread group 1-2] org.apache.jmeter.threads.JMeterThread   : Thread is done: RootRetrievalList thread group 1-2
2017-12-14 11:10:00.058  INFO   --- [hread group 1-2] org.apache.jmeter.threads.JMeterThread   : Thread finished: RootRetrievalList thread group 1-2
com.trgr.quality.scale.testcases.marduk.RetrieveRootsV2: Exiting tearDown() at: Thu Dec 14 11:10:00 CST 2017
2017-12-14 11:10:00.193  INFO   --- [hread group 1-1] org.apache.jmeter.threads.JMeterThread   : Thread is done: RootRetrievalList thread group 1-1
2017-12-14 11:10:00.194  INFO   --- [hread group 1-1] org.apache.jmeter.threads.JMeterThread   : Thread finished: RootRetrievalList thread group 1-1
2017-12-14 11:10:00.195  INFO   --- [ardJMeterEngine] o.a.jmeter.engine.StandardJMeterEngine   : Notifying test listeners of end of test
2017-12-14 11:10:00.202  INFO   --- [ardJMeterEngine] org.apache.jmeter.reporters.Summariser   : summary +      1 in 00:00:00 =    6.8/s Avg:   207 Min:   207 Max:   207 Err:     0 (0.00%) Active: 0 Started: 2 Finished: 2
summary +      1 in 00:00:00 =    6.8/s Avg:   207 Min:   207 Max:   207 Err:     0 (0.00%) Active: 0 Started: 2 Finished: 2
2017-12-14 11:10:00.203  INFO   --- [ardJMeterEngine] org.apache.jmeter.reporters.Summariser   : summary =      2 in 00:00:04 =    0.5/s Avg:   196 Min:   186 Max:   207 Err:     0 (0.00%)
summary =      2 in 00:00:04 =    0.5/s Avg:   196 Min:   186 Max:   207 Err:     0 (0.00%)
Tidying up ...    @ Thu Dec 14 11:10:00 CST 2017 (1513271400204)
... end of run

BUILD SUCCESSFUL

Total time: 1 mins 25.767 secs

```

**Comment by foragerr** [comment]
Could I also ask you to try and launch a test on the problem ec2 box directly from JMeter without going through the plugin? That'll help determine if it's a JMeter issue or something this plugin introduces.

If you're using a public AMI, can you share, please? so I can try to repro.

**Comment by cmacgowan** [comment]
Sure - I'll give that a try ... we are calling from Thomson Reuters - so the AMI is not public :--( 
Also - I'm a contractor working on my last day here ... my colleague(s) may join the discussion. But if the thread goes dead ... you'll know what happened. Thanks again for your work on the plug-in!
