### ISSUE TITLE
Running a simple test I am getting "Can't read log file"

### ISSUE THREAD

**Issue by jhalehol** [jmeter-gradle-plugin/jmeter-gradle-plugin#117]
Hi guys, I am trying to run a simple test, with the version 1.0.10-3.3, but I am getting this error: "Can't read log file", I tried to set up these parameters (ignoreErrors, jmLog, ignoreFailures), to avoid this error but they don't works,  next a complete stacktrace: 

> at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: Can't read log file

> Caused by: java.io.FileNotFoundException: /Users/Jhon-Aleck/source/devspaces-test-hardness/build/jmeter-report/DVSP-2531-Thread.jmx-20180424-1121.csv (No such file or directory)
        at net.foragerr.jmeter.gradle.plugins.utils.ErrorScanner.scanForProblems(ErrorScanner.groovy:26)
        at net.foragerr.jmeter.gradle.plugins.utils.ErrorScanner$scanForProblems.call(Unknown Source)

**Comment by ghost** [comment]
Looking at the stacktrace, your csv file cannot be found.  Is this path valid:  Users/Jhon-Aleck/source/devspaces-test-hardness/build/jmeter-report/DVSP-2531-Thread.jmx-20180424-1121.csv ?
