### ISSUE TITLE
Issue when running jmReport

### ISSUE THREAD

**Issue by cfalba80** [jmeter-gradle-plugin/jmeter-gradle-plugin#17]
Hello foragger,

thanks for your help, i have another question, when running "gradle jmReport" i am getting this error now:

```
Caused by: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method org.apache.tools.ant.DirectoryScanner#setBasedir.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
[class java.io.File]
[class java.lang.String]
at net.foragerr.jmeter.gradle.plugins.utils.JMUtils.scanDir(JMUtils.groovy:33)
at net.foragerr.jmeter.gradle.plugins.utils.JMUtils$scanDir.call(Unknown Source)
at net.foragerr.jmeter.gradle.plugins.TaskJMReports.jmCreateReport(TaskJMReports.groovy:44)
```

this is my build.gradle:

```
apply plugin: 'net.foragerr.jmeter'
buildscript {
    repositories { 
        mavenCentral()
        maven {url 'https://dl.bintray.com/jmeter-gradle-plugin/jmeter'}
    }
    dependencies {
        classpath "net.foragerr.jmeter:jmeter-gradle-plugin:0.5.2-2.13"
    }
}

jmeter {
    jmTestFiles = [file("src/test/Load&ReviewReceipts.jmx")]
    jmPropertyFile = file("src/test/jmeter.properties")
    enableReports = true
}
```

maybe it is a config issue?

Thank you.

**Comment by foragerr** [comment]
Thanks for the bug report. Please try now with v0.5.4

**Comment by cfalba80** [comment]
Hello foragerr,

thanks again, one question, is it possible with this plugin to generate a composite html with all the graphs generated?

Thanks

**Comment by djangofan** [comment]
If you do generate a composite 'index.html', which sounds like it would be useful,  please keep it separate from the standalone *-report.html file that is currently being generated.  This is for purposes of allowing Jenkins to archive the latter mentioned file with the "HTML Publisher" plugin.

**Comment by foragerr** [comment]
Not currently, no. However, @djangofan requested the same feature as well earlier [here](https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/issues/6) You should watch issue #6 for updates.

I'll look into that, probably this weekend.

**Comment by cfalba80** [comment]
Ok, thanks.

I have another issue, need to integrate this plugin in an existing gradle project wich has another classpath dependency configured, when i add the classpath for this plugin i am getting this error when trying to run jmRun:
Caused by: java.io.IOException: Cannot run program "java" (in directory "D:\workspace_gap\TestJmeter\build\jmeter"): CreateProcess error=206, The filename or extension is too long
        at java_lang_ProcessBuilder$start$2.call(Unknown Source)
        at net.foragerr.jmeter.gradle.plugins.worker.JMeterRunner.launchProcess(JMeterRunner.groovy:16)
        at net.foragerr.jmeter.gradle.plugins.worker.JMeterRunner.executeJmeterCommand(JMeterRunner.groovy:25)
        at net.foragerr.jmeter.gradle.plugins.worker.JMeterRunner$executeJmeterCommand.call(Unknown Source)
        at net.foragerr.jmeter.gradle.plugins.TaskJMRun.executeJmeterTest(TaskJMRun.groovy:104)
        ... 57 more
Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
        ... 62 more

The classpath overflows when trying to add this and the java process fails.
This is  the build.gradle:
apply plugin: 'net.foragerr.jmeter'

buildscript {
    repositories { 
        mavenCentral()
        maven {url 'https://dl.bintray.com/jmeter-gradle-plugin/jmeter'}
          maven { url 'http://artifactory.gapinc.dev/artifactory/remote-repos' }
        ivy {
            layout 'maven'
            url 'http://artifactory.gapinc.dev/artifactory/remote-repos'
        }
    }
    dependencies {
        classpath 'com.gap:gap-gradle-plugin:+'
        classpath "net.foragerr.jmeter:jmeter-gradle-plugin:0.5.4-2.13"
    }

}
jmeter {
    jmTestFiles = [file("src/test/Load&ReviewReceipts.jmx")]
    jmPropertyFile = file("src/test/jmeter.properties")
    enableReports = false
    enableExtendedReports = true 

}

**Comment by foragerr** [comment]
Can you put this in a new issue please?

**Comment by cfalba80** [comment]
Hi,

done, issue #18 
Thanks
