### ISSUE TITLE
Putting a doFirst clause in the jmeter task breaks the build

### ISSUE THREAD

**Issue by djangofan** [jmeter-gradle-plugin/jmeter-gradle-plugin#25]
Putting a doFirst clause in the jmeter task breaks the build.  Here is output from my job , which contains a doFirst clause in the jmeter task.  You can reproduce by putting a empty doFirst {}  clause in the jmeter task in the  advanced example in this same jmeter-gradle-plugin account.

With the Kulya plugin, I was able to add a doFirst clause in the jmeter.configure task.

```
Running Jmeter GUI from Gradle...


FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\rXXXXX\IdeaProjects\cost-test\PROJ-jmeter-tests\build.gradle' line: 32

* What went wrong:
A problem occurred evaluating root project 'PROJ-jmeter-tests'.
> Could not find method doFirst() for arguments [build_7ywtilwed7eepc0ls9ybfr128$_run_closure1_closure5@12874b23] on root project 'PROJ-jmeter-tests'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'PROJ-jmeter-tests'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:76)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$1.run(DefaultScriptPluginFactory.java:148)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:156)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:487)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:85)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.api.internal.MissingMethodException: Could not find method doFirst() for arguments [build_7ywtilwed7eepc0ls9ybfr128$_run_closure1_closure5@12874b23] on
root project 'PROJ-jmeter-tests'.
        at org.gradle.api.internal.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:68)
        at org.gradle.api.internal.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:56)
        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:175)
        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
        at build_7ywtilwed7eepc0ls9ybfr128$_run_closure1.doCall(C:\Users\r626095\IdeaProjects\cost-test\PROJ-jmeter-tests\build.gradle:32)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
        at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
        at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
        at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:207)
        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:150)
        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
        at build_7ywtilwed7eepc0ls9ybfr128.run(C:\Users\r626095\IdeaProjects\cost-test\PROJ-jmeter-tests\build.gradle:30)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:74)
        ... 38 more


BUILD FAILED
```

**Comment by foragerr** [comment]
What are you doing in your doFirst closure?

**Comment by djangofan** [comment]
Anything or nothing...

**Comment by foragerr** [comment]
`doFirst` wouldn't go into the `jmeter` config section, instead should be associated with a task. For instance you can add:

```
jmReport.doFirst{
    println 'Print Me First!'
}
```

will print the string when jmReport is run.

**Comment by djangofan** [comment]
@foragerr  Keep in mind that the reason I know it should work this way is that I can do it with the old Kulya  jmeter-gradle-plugin .   I believe  putting a doFirst clause in a task is a very 'standard' way of doing things with Gradle.   I am not convinced that  jmReport.doFirst  is equivilant, and even if it is, why leave something that "should work" broken?

Its easy to see what I say is true.  Just download the project located here and run the 'startJmeterWithGradle.bat' script:  https://github.com/djangofan/launch-jmeter

**Comment by foragerr** [comment]
`doFirst` can only be added to a task. The config in build.gradle  for kulya plugin is specifically for the jmeterRun **task**. 

```
jmeterRun.configure {
}
```

adding a `doFirst` to that, adds it to the jmeterRun task. The equivalent way to do that in this plugin is to do:

```
jmRun{
    doFirst{}
}
```

This hasn't changed.

What you're trying to do is add `doFirst` to this snippet

```
jmeter {
}
```

`jmeter` here isn't a task at all, but is configuration for the entire plugin via [Extensions](https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/ExtensionContainer.html)

**Comment by djangofan** [comment]
@foragerr   Ack.  That is really confusing.  Sorry, not sure how I would have known that difference without a deep investigation.    So, now my question is "why" did you choose not to use the Extensions way of doing it?   What is the real difference here?   What do you recommend on this and can it be documented in the README?
