### ISSUE TITLE
ERROR - jmeter.threads.JMeterThread: Test failed! java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal

### ISSUE THREAD

**Issue by seungchanlee** [jmeter-gradle-plugin/jmeter-gradle-plugin#47]
I wonder how to remove this exception??  Any idea?  It would be very appreciated!!

build file -- 

plugins {
    id "net.foragerr.jmeter" version "1.0-2.13"
}
apply plugin: 'java'

jmeter {
    jmTestFiles = [file("src/test/jmeter/DiceTest.jmx")]
    jmUserPropertiesFiles = [file("src/test/jmeter/user.properties")]
    enableExtendedReports = true
}

Exception - 

ERROR - jmeter.threads.JMeterThread: Test failed! java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.apache.xerces.parsers.AbstractDOMParser.startDocument(Unknown Source)
    at org.apache.xerces.impl.dtd.XMLDTDValidator.startDocument(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentScannerImpl.startEntity(Unknown Source)
    at org.apache.xerces.impl.XMLVersionDetector.startDocumentParsing(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
    at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
    at org.apache.jmeter.util.XPathUtil.makeDocument(XPathUtil.java:177)
    at org.apache.jmeter.util.XPathUtil.makeDocument(XPathUtil.java:145)
    at org.apache.jmeter.extractor.XPathExtractor.parseResponse(XPathExtractor.java:302)
    at org.apache.jmeter.extractor.XPathExtractor.process(XPathExtractor.java:142)
    at org.apache.jmeter.threads.JMeterThread.runPostProcessors(JMeterThread.java:750)
    at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:452)
    at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:261)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 30 more

**Comment by seungchanlee** [comment]
The http request sending is ok ...  the response is xml ...  when I try to use XPath expression to retrieve attribute values, I'm getting this exception ...  Looks like I'm missing some jmeter plugins or something ...  I changed my build file, but still getting the same exception ...

buildscript {
    ext {
        pluginsVersion = "1.3.0"
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.codehaus.groovy:groovy-all:2.4.3"

```
    classpath (group: 'kg.apc', name: 'jmeter-plugins-standard', version: pluginsVersion) {
            exclude group: 'commons-math3', module: 'commons-math3'
            exclude group: 'commons-pool2', module: 'commons-pool2'
    }
    classpath(group: 'kg.apc', name: 'jmeter-plugins-common', version: pluginsVersion) {
        exclude group: 'commons-math3', module: 'commons-math3'
        exclude group: 'commons-pool2', module: 'commons-pool2'
    }

    classpath(group: 'kg.apc', name: 'jmeter-plugins-extras', version: pluginsVersion) {
        exclude group: 'commons-math3', module: 'commons-math3'
        exclude group: 'commons-pool2', module: 'commons-pool2'
    }

    classpath(group: 'kg.apc', name: 'jmeter-plugins-extras-libs', version: pluginsVersion) {
        exclude group: 'commons-math3', module: 'commons-math3'
        exclude group: 'commons-pool2', module: 'commons-pool2'
    }

    classpath(group: 'kg.apc', name: 'jmeter-plugins-webdriver', version: pluginsVersion) {
        exclude group: 'commons-math3', module: 'commons-math3'
        exclude group: 'commons-pool2', module: 'commons-pool2'
    }

}
```

}

plugins {
    id "net.foragerr.jmeter" version "1.0-2.13"
}
apply plugin: 'java'

jmeter {
    jmTestFiles = [file("src/test/jmeter/DiceTest.jmx")]
    jmUserPropertiesFiles = [file("src/test/jmeter/user.properties")]
    enableExtendedReports = true
    jmPluginJars = ["groovy-all",
                        "jmeter-plugins-standard",
                        "jmeter-plugins-common",
                        "jmeter-plugins-extras",
                        "jmeter-plugins-extras-libs",
                        "jmeter-plugins-webdriver"]
}

**Comment by foragerr** [comment]
Hi, are you able to run the test without errors from regular jmeter? (without going through the plugin)

**Comment by foragerr** [comment]
Can you try adding this dependency to jmeter classpath? http://mvnrepository.com/artifact/xml-apis/xml-apis/1.4.01

**Comment by seungchanlee** [comment]
Thanks for the reply!

Yes I can run my jmeter test using the reqular jmeter ...

'Adding the dependency to jmeter classpath' - I'm not sure what you meant jmeter classpath??  Could you tell me where exactly to add it?  It would be very appreciated!!

**Comment by seungchanlee** [comment]
I tried to put xml-api-1.4.01.jar in  {projectDIr}/build/jmeter/lib folder ... no difference ....  tried put in  {projectDIr}/build/jmeter/lib/ext ... still no difference ...

**Comment by foragerr** [comment]
Would it be possible to give me a simple jmx file that I can use to reproduce this issue?

**Comment by seungchanlee** [comment]
I just create a HTTP Request and XPath Extractor.  I just removed confidential info from this jmx, but you still have an idea ...  The below xml is an example response and xpath extractor tries to retrieve clientId from it.

[DiceTest.zip](https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/files/190904/DiceTest.zip)

<registerClientResponse enterpriseId="entid" clientId="00e2b6ea-97cb-4c3c-9a72-023abaed4ba7" token="127.0.0.1:testhost1" />

I found out last night ...  the xml-apis.jar version that is included in buildscript configuration classpath is 2.0.2 (the latest) instead of 1.4.01 ...  so I wondered if this newer xml-apis.jar conflicts with others ...  I'm not sure how I include 1.4 instead of 2.0.2 ...

(truncated for readability)

**Comment by foragerr** [comment]
`xml-apis-2.0.2` does not contain `org/w3c/dom/ElementTraversal` which apparently xpath extractor requires. There are different components in Jmeter which are variously using `xml-apis-1.4.01` and `xml-apis-2.0.2`. Gradle's dependency resolution strategy automatically uses the newest version of a dependency everywhere, if there is a version conflict - which is the cause of your issue.

As a workaround, you can try forcing gradle to use 1.4.01 instead of 2.0.2, but this will have to be in the  buildscript section of your build.gradle. Which in turn means you will have to fall back to the older way to add a plugin to your script.

Putting all of that together, in your build.gradle, replace:

```
plugins {
    id "net.foragerr.jmeter" version "1.0-2.13"
}
```

with

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "net.foragerr.jmeter:jmeter-gradle-plugin:1.0.3-2.13"
    }
    configurations.all {
        resolutionStrategy {
            force 'xml-apis:xml-apis:1.4.01' //force usage of v1.4.01
        }
    }
}
```

**Comment by seungchanlee** [comment]
thanks a lot!  works fine now!
