### ISSUE TITLE
JmeterEditor task is broken

### ISSUE THREAD

**Issue by foragerr** [jmeter-gradle-plugin/jmeter-gradle-plugin#5]
```
Execution failed for task ':jmeterEditor'.
> Cannot invoke method getCanonicalPath() on null object
```

**Comment by foragerr** [comment]
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jmeterEditor'.
    Caused by: java.lang.NullPointerException: Cannot invoke method getCanonicalPath() on null object
        at net.foragerr.jmeter.gradle.plugins.JmeterRunGuiTask.runTaskAction(JmeterRunGuiTask.groovy:31)
        at net.foragerr.jmeter.gradle.plugins.JmeterAbstractTask.start(JmeterAbstractTask.groovy:53)
```

**Comment by foragerr** [comment]
Only happens if `jmeter.properties` file is not supplied
