### ISSUE TITLE
Unable to find mysql jdbc driver

### ISSUE THREAD

**Issue by winston-lee** [jmeter-gradle-plugin/jmeter-gradle-plugin#77]
Hi, I wrote a very simple jdbc test and it was working in a standalone jmeter. But when I use the embedded jmeter using jmGui, it fails. Here's a snippet of the debug:

2016/06/26 09:44:31 INFO  - jmeter.testelement.TestPlan: add /tmp/mysql-connector-java-5.1.38.jar to classpath 
2016/06/26 09:44:31 DEBUG - jmeter.protocol.jdbc.config.DataSourceElement: MaxPool: 10 Timeout: 10000 TrimInt: 60000 Auto-Commit: true 
2016/06/26 09:44:31 DEBUG - jmeter.protocol.jdbc.config.DataSourceElement: KeepAlive: true Age: 5000 CheckQuery: Select 1 
2016/06/26 09:44:31 DEBUG - jmeter.protocol.jdbc.config.DataSourceElement: Driver: com.mysql.jdbc.Driver DbUrl: jdbc:mysql://localhost:3306/foobar User: test 
2016/06/26 09:44:31 DEBUG - jmeter.protocol.jdbc.config.DataSourceElement: Loading new driver: com.mysql.jdbc.Driver 
2016/06/26 09:44:31 INFO  - jmeter.gui.util.JMeterMenuBar: setRunning(true,_local_) 
2016/06/26 09:44:31 INFO  - jmeter.engine.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group 
2016/06/26 09:44:31 INFO  - jmeter.engine.StandardJMeterEngine: Starting 1 threads for group Thread Group. 
2016/06/26 09:44:31 INFO  - jmeter.engine.StandardJMeterEngine: Thread will continue on error 
2016/06/26 09:44:31 INFO  - jmeter.threads.ThreadGroup: Starting thread group number 1 threads 1 ramp-up 1 perThread 1000.0 delayedStart=false 
2016/06/26 09:44:31 INFO  - jmeter.threads.JMeterThread: jmeterthread.startearlier=true (see jmeter.properties) 
2016/06/26 09:44:31 INFO  - jmeter.threads.JMeterThread: Running PostProcessors in forward order 
2016/06/26 09:44:31 INFO  - jmeter.threads.ThreadGroup: Started thread group number 1 
2016/06/26 09:44:31 INFO  - jmeter.engine.StandardJMeterEngine: All thread groups have been started 
2016/06/26 09:44:31 INFO  - jmeter.threads.JMeterThread: Thread started: Thread Group 1-1 
2016/06/26 09:44:31 DEBUG - jmeter.protocol.jdbc.sampler.JDBCSampler: sampling jdbc 
2016/06/26 09:44:31 DEBUG - jmeter.protocol.jdbc.config.DataSourceElement: Marking 0 objects as old in pool. 
2016/06/26 09:44:31 WARN  - jmeter.protocol.jdbc.config.DataSourceElement: Could not return Connection java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/foobar
    at java.sql.DriverManager.getConnection(DriverManager.java:689)
    at java.sql.DriverManager.getConnection(DriverManager.java:247)
    at org.apache.avalon.excalibur.datasource.JdbcConnectionFactory.newInstance(JdbcConnectionFactory.java:182)
    at org.apache.avalon.excalibur.pool.InstrumentedResourceLimitingPool.newPoolable(InstrumentedResourceLimitingPool.java:655)
    at org.apache.avalon.excalibur.pool.ValidatedResourceLimitingPool.newPoolable(ValidatedResourceLimitingPool.java:145)
    at org.apache.avalon.excalibur.datasource.ResourceLimitingJdbcConnectionPool.newPoolable(ResourceLimitingJdbcConnectionPool.java:91)
    at org.apache.avalon.excalibur.pool.InstrumentedResourceLimitingPool.get(InstrumentedResourceLimitingPool.java:371)
    at org.apache.avalon.excalibur.pool.ValidatedResourceLimitingPool.get(ValidatedResourceLimitingPool.java:97)
    at org.apache.avalon.excalibur.datasource.ResourceLimitingJdbcDataSource.getConnection(ResourceLimitingJdbcDataSource.java:188)
    at org.apache.jmeter.protocol.jdbc.config.DataSourceElement$DataSourceComponentImpl.getConnection(DataSourceElement.java:286)
    at org.apache.jmeter.protocol.jdbc.config.DataSourceElement.getConnection(DataSourceElement.java:146)
    at org.apache.jmeter.protocol.jdbc.sampler.JDBCSampler.sample(JDBCSampler.java:85)
    at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:434)
    at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:261)
    at java.lang.Thread.run(Thread.java:745)

**Comment by foragerr** [comment]
Can you provide a sample jmx file that reproduces this issue?

**Comment by winston-lee** [comment]
Hi there,

Attached is a sample file. You will have to create a mysql user with username/password as testuser/testuser and create a db schema auth-service. You will also need to create a table called user_account with an email field.

Also, please download the appropriate mysql JDBC driver such as mysql-connector-java-5.1.38.jar and add the path into the test script.

[jdbc.jmx.zip](https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/files/333510/jdbc.jmx.zip)

Thanks.

**Comment by winston-lee** [comment]
Can I also add that I've even tried putting the jar into build/jmeter/lib directory and that doesn't work either.

**Comment by foragerr** [comment]
It turns out, I'm adding both bin and bin/ext to jmeter classpath, but I cant add a folder to classpath, need to put a wildcard in there as well =/

Thanks for finding this issue, will roll out a fix soon.

**Comment by foragerr** [comment]
issue fixed in release v1.0.6, please verify when you get a chance. Driver jar needs to be dropped into `build/jmeter/lib`. There is still a problem with this, if you run `gradle jmClean`, the jar in `build/jmeter/lib` will get deleted. Raising a new issue for that.

**Comment by winston-lee** [comment]
Thanks heaps foragerr! Works like a charm! Cheers!
